package com.greenself.daogen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greenself.daogen.Task;
import com.greenself.daogen.TaskSource;
import com.greenself.daogen.TaskHistory;

import com.greenself.daogen.TaskDao;
import com.greenself.daogen.TaskSourceDao;
import com.greenself.daogen.TaskHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskSourceDaoConfig;
    private final DaoConfig taskHistoryDaoConfig;

    private final TaskDao taskDao;
    private final TaskSourceDao taskSourceDao;
    private final TaskHistoryDao taskHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskSourceDaoConfig = daoConfigMap.get(TaskSourceDao.class).clone();
        taskSourceDaoConfig.initIdentityScope(type);

        taskHistoryDaoConfig = daoConfigMap.get(TaskHistoryDao.class).clone();
        taskHistoryDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        taskSourceDao = new TaskSourceDao(taskSourceDaoConfig, this);
        taskHistoryDao = new TaskHistoryDao(taskHistoryDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(TaskSource.class, taskSourceDao);
        registerDao(TaskHistory.class, taskHistoryDao);
    }
    
    public void clear() {
        taskDaoConfig.getIdentityScope().clear();
        taskSourceDaoConfig.getIdentityScope().clear();
        taskHistoryDaoConfig.getIdentityScope().clear();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskSourceDao getTaskSourceDao() {
        return taskSourceDao;
    }

    public TaskHistoryDao getTaskHistoryDao() {
        return taskHistoryDao;
    }

}
