package com.greenself.daogen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greenself.daogen.Task;
import com.greenself.daogen.Habbit;

import com.greenself.daogen.TaskDao;
import com.greenself.daogen.HabbitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig habbitDaoConfig;

    private final TaskDao taskDao;
    private final HabbitDao habbitDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        habbitDaoConfig = daoConfigMap.get(HabbitDao.class).clone();
        habbitDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        habbitDao = new HabbitDao(habbitDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(Habbit.class, habbitDao);
    }
    
    public void clear() {
        taskDaoConfig.getIdentityScope().clear();
        habbitDaoConfig.getIdentityScope().clear();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public HabbitDao getHabbitDao() {
        return habbitDao;
    }

}
