package com.greenself.daogen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HABBIT.
 */
public class Habbit {

    private Long id;
    /** Not-null value. */
    private String actvity;
    private Integer type;
    private Boolean applicability;
    private Boolean status;
    private String info;
    private java.util.Date date;
    private String motivation;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Habbit() {
    }

    public Habbit(Long id) {
        this.id = id;
    }

    public Habbit(Long id, String actvity, Integer type, Boolean applicability, Boolean status, String info, java.util.Date date, String motivation) {
        this.id = id;
        this.actvity = actvity;
        this.type = type;
        this.applicability = applicability;
        this.status = status;
        this.info = info;
        this.date = date;
        this.motivation = motivation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getActvity() {
        return actvity;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActvity(String actvity) {
        this.actvity = actvity;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Boolean getApplicability() {
        return applicability;
    }

    public void setApplicability(Boolean applicability) {
        this.applicability = applicability;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getMotivation() {
        return motivation;
    }

    public void setMotivation(String motivation) {
        this.motivation = motivation;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
