package com.greenself.daogen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table QUOTE.
 */
public class Quote {

    private Long id;
    private String text;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Quote() {
    }

    public Quote(Long id) {
        this.id = id;
    }

    public Quote(Long id, String text) {
        this.id = id;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    // KEEP METHODS - put your custom methods here
    public Quote(String text) {
    	this.text = text;
    }    
    // KEEP METHODS END

}
