package com.greenself.daogen;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.greenself.daogen.TaskSource;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TASK_SOURCE.
*/
public class TaskSourceDao extends AbstractDao<TaskSource, Long> {

    public static final String TABLENAME = "TASK_SOURCE";

    /**
     * Properties of entity TaskSource.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TypeDB = new Property(1, String.class, "typeDB", false, "TYPE_DB");
        public final static Property Applicability = new Property(2, Boolean.class, "applicability", false, "APPLICABILITY");
        public final static Property Info = new Property(3, String.class, "info", false, "INFO");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
    };


    public TaskSourceDao(DaoConfig config) {
        super(config);
    }
    
    public TaskSourceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TASK_SOURCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TYPE_DB' TEXT," + // 1: typeDB
                "'APPLICABILITY' INTEGER," + // 2: applicability
                "'INFO' TEXT," + // 3: info
                "'NAME' TEXT NOT NULL );"); // 4: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TASK_SOURCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TaskSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String typeDB = entity.getTypeDB();
        if (typeDB != null) {
            stmt.bindString(2, typeDB);
        }
 
        Boolean applicability = entity.getApplicability();
        if (applicability != null) {
            stmt.bindLong(3, applicability ? 1l: 0l);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(4, info);
        }
        stmt.bindString(5, entity.getName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TaskSource readEntity(Cursor cursor, int offset) {
        TaskSource entity = new TaskSource( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // typeDB
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // applicability
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // info
            cursor.getString(offset + 4) // name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TaskSource entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTypeDB(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setApplicability(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setInfo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TaskSource entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TaskSource entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
