package com.greenself.daogen;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.greenself.objects.Constants.Recurrence;
// KEEP INCLUDES END
/**
 * Entity mapped to table TASK.
 */
public class Task {

    private Long id;
    /** Not-null value. */
    private String actvity;
    private String recurrenceDB;
    private Boolean applicability;
    private Boolean status;
    private String info;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    private Recurrence recurrence;
    // KEEP FIELDS END

    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    public Task(Long id, String actvity, String recurrenceDB, Boolean applicability, Boolean status, String info, java.util.Date date) {
        this.id = id;
        this.actvity = actvity;
        this.recurrenceDB = recurrenceDB;
        this.applicability = applicability;
        this.status = status;
        this.info = info;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getActvity() {
        return actvity;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setActvity(String actvity) {
        this.actvity = actvity;
    }

    public String getRecurrenceDB() {
        return recurrenceDB;
    }

    public void setRecurrenceDB(String recurrenceDB) {
        this.recurrenceDB = recurrenceDB;
    }

    public Boolean getApplicability() {
        return applicability;
    }

    public void setApplicability(Boolean applicability) {
        this.applicability = applicability;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    public void setType(Recurrence recurrence) {
    	this.recurrenceDB = recurrence.name();
    	this.recurrence = recurrence;
    }
    public Recurrence getRecurrence() {
    	if(this.recurrence==null) {
	    	try {
	    		this.recurrence = Recurrence.valueOf(this.recurrenceDB);
	    	} catch (Exception ex) {
	    		ex.printStackTrace();
	    		this.recurrence = Recurrence.DAILY;
	    	}
    	}
    	
    	return this.recurrence;
    }
    // KEEP METHODS END

}
