package com.greenself.daogen;

import com.greenself.daogen.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TASK.
 */
public class Task {

    private boolean status;
    private Boolean visible;
    private java.util.Date date;
    private long id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TaskDao myDao;

    private TaskSource taskSource;
    private Long taskSource__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Task() {
    }

    public Task(long id) {
        this.id = id;
    }

    public Task(boolean status, Boolean visible, java.util.Date date, long id) {
        this.status = status;
        this.visible = visible;
        this.date = date;
        this.id = id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTaskDao() : null;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public Boolean getVisible() {
        return visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** To-one relationship, resolved on first access. */
    public TaskSource getTaskSource() {
        long __key = this.id;
        if (taskSource__resolvedKey == null || !taskSource__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TaskSourceDao targetDao = daoSession.getTaskSourceDao();
            TaskSource taskSourceNew = targetDao.load(__key);
            synchronized (this) {
                taskSource = taskSourceNew;
            	taskSource__resolvedKey = __key;
            }
        }
        return taskSource;
    }

    public void setTaskSource(TaskSource taskSource) {
        if (taskSource == null) {
            throw new DaoException("To-one property 'id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.taskSource = taskSource;
            id = taskSource.getId();
            taskSource__resolvedKey = id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // custom constructor
    public Task(boolean status, boolean visible, java.util.Date date, TaskSource taskSource) {
        this.status = status;
        this.date = date;
        this.visible = visible;
        setTaskSource(taskSource);
    }
    // KEEP METHODS END

}
